/**
 * Escalation marker step. Records the reason and flips status to ESCALATED;
 * the actual escalation letter is generated by the next pursueGrievance
 * recursion (called with isEscalation=true), which routes through draft +
 * approve + send again.
 */

import { remember } from "@/lib/mubit";
import { appendTimelineEvent, markStatus } from "@/lib/store";

import type { GrievanceResearch } from "@/types/grievance";

export type EscalationReason = "deadline_lapsed" | "rejection" | "unhandled_reply";

const REASON_SUMMARY: Record<EscalationReason, string> = {
  deadline_lapsed: "Response deadline lapsed without reply",
  rejection: "Outright rejection received — escalating",
  unhandled_reply: "Reply could not be classified — escalating",
};

export async function escalateStep(input: {
  grievanceId: string;
  reason: EscalationReason;
  research: GrievanceResearch;
}): Promise<void> {
  "use step";

  await markStatus(input.grievanceId, "ESCALATED");

  await appendTimelineEvent(input.grievanceId, {
    at: new Date().toISOString(),
    kind: "escalated",
    summary: REASON_SUMMARY[input.reason] +
      (input.research.regulatorName ? ` to ${input.research.regulatorName}` : ""),
    payload: {
      reason: input.reason,
      regulatorName: input.research.regulatorName,
      regulatorUrl: input.research.regulatorUrl,
    },
  });

  await remember({
    grievanceId: input.grievanceId,
    kind: "decision",
    content: `Escalating: ${REASON_SUMMARY[input.reason]}. Regulator: ${input.research.regulatorName ?? "(unknown)"}.`,
  });
}
